# Generated by Django 3.0.7 on 2020-07-03 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('chaptername', models.CharField(max_length=50)),
                ('sectionname', models.CharField(max_length=50)),
                ('termname', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bunchrelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatepages', models.CharField(max_length=7, unique=True)),
                ('slideheader', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bunch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factors.Bunch')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jslidepage', models.CharField(max_length=2, unique=True)),
                ('template', models.CharField(max_length=50)),
                ('image1', models.CharField(blank=True, max_length=50, null=True)),
                ('image3', models.CharField(blank=True, max_length=50, null=True)),
                ('image4', models.CharField(blank=True, max_length=50, null=True)),
                ('image5', models.CharField(blank=True, max_length=50, null=True)),
                ('image6', models.CharField(blank=True, max_length=50, null=True)),
                ('image7', models.CharField(blank=True, max_length=50, null=True)),
                ('image8', models.CharField(blank=True, max_length=50, null=True)),
                ('footertext1', models.CharField(blank=True, max_length=50, null=True)),
                ('footericon1', models.CharField(blank=True, max_length=50, null=True)),
                ('footertext2', models.CharField(blank=True, max_length=50, null=True)),
                ('footericon2', models.CharField(blank=True, max_length=50, null=True)),
                ('footertext3', models.CharField(blank=True, max_length=50, null=True)),
                ('footericon3', models.CharField(blank=True, max_length=50, null=True)),
                ('footertext4', models.CharField(blank=True, max_length=50, null=True)),
                ('footericon4', models.CharField(blank=True, max_length=50, null=True)),
                ('footertext5', models.CharField(blank=True, max_length=50, null=True)),
                ('footericon5', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bunchrelate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factors.Bunchrelate')),
            ],
        ),
    ]
